#!/usr/bin/env node
/**
 * 离线测试用假 npm：只支持 `pack <spec> --pack-destination <dir>`。
 * 版本解析 = 真实 skills.json 清单（与 CLI 同源）：range `X.x` -> 清单精确版本；精确版本 -> 原样。
 * 生成一个最小合法技能 tgz（SKILL.md 版本写入解析后版本），并记录每次 argv 到 YOTTA_SKILLS_FAKE_LOG。
 */
'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawnSync } = require('child_process');

const logFile = process.env.YOTTA_SKILLS_FAKE_LOG || null;
const args = process.argv.slice(2);
if (logFile) fs.appendFileSync(logFile, JSON.stringify(args) + '\n');

const i = args.indexOf('pack');
if (i === -1) { process.stderr.write('fake-npm: 仅支持 pack\n'); process.exit(1); }
const spec = args[i + 1];
const m = spec.match(/^(@[^@/]+\/[^@]+)@(.+)$/);
if (!m) { process.stderr.write('fake-npm: 无法解析 spec ' + spec + '\n'); process.exit(1); }
const pkg = m[1];
const range = m[2];

const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'skills.json'), 'utf8'));
const list = Array.isArray(manifest) ? manifest : manifest.skills;
const entry = list.find(s => s.pkg === pkg);
if (!entry) { process.stderr.write('fake-npm: 清单无此包 ' + pkg + '\n'); process.exit(1); }

const exact = /^[0-9]+\.[0-9]+\.[0-9]+$/.test(range);
const version = exact ? range : entry.version;
if (!exact) {
  const major = String(version).split('.')[0];
  if (range !== major + '.x') { process.stderr.write('fake-npm: 不支持的范围 ' + range + '\n'); process.exit(1); }
}

const destIdx = args.indexOf('--pack-destination');
const outDir = destIdx !== -1 ? args[destIdx + 1] : process.cwd();
fs.mkdirSync(outDir, { recursive: true });

const scopeName = pkg.split('/')[0].replace('@', '');
const bare = pkg.split('/')[1];
const fname = scopeName + '-' + bare + '-' + version + '.tgz';
const tgz = path.join(outDir, fname);

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'fake-npm-'));
const pkgRoot = path.join(tmp, 'package');
for (const d of ['references', 'scripts', 'assets', 'bin']) fs.mkdirSync(path.join(pkgRoot, d), { recursive: true });

const skill = [
  '---', 'name: ' + bare, 'version: ' + version,
  'description: fake skill for offline yotta-skills tests (slug ' + bare + ')',
  'license: MIT', '---', '', '# ' + bare, '',
  'Fake skill package generated by test/helpers/fake-npm.js.',
].join('\n') + '\n';
fs.writeFileSync(path.join(pkgRoot, 'SKILL.md'), skill, 'utf8');
fs.writeFileSync(path.join(pkgRoot, 'README.md'), '# ' + bare + '\n\nfake readme\n', 'utf8');
fs.writeFileSync(path.join(pkgRoot, 'references', 'install.md'), '## install\n\nnpx -y ' + pkg + '\n', 'utf8');
fs.writeFileSync(path.join(pkgRoot, 'scripts', 'demo.py'), 'print("' + bare + '")\n', 'utf8');
fs.writeFileSync(path.join(pkgRoot, 'assets', 'marker.txt'), bare + ' ' + version + '\n', 'utf8');
// 安装时应被跳过的文件（验证 skip 集合）
fs.writeFileSync(path.join(pkgRoot, 'package.json'), JSON.stringify({ name: pkg, version }, null, 2) + '\n', 'utf8');
fs.writeFileSync(path.join(pkgRoot, 'bin', 'extra.js'), '#!/usr/bin/env node\nconsole.log(1);\n', 'utf8');
// 缓存/编译产物：安装时应被跳过（元信 scan 会产生 __pycache__）
fs.mkdirSync(path.join(pkgRoot, 'scripts', '__pycache__'), { recursive: true });
fs.writeFileSync(path.join(pkgRoot, 'scripts', '__pycache__', 'demo.cpython-38.pyc'), 'x', 'utf8');
fs.writeFileSync(path.join(pkgRoot, 'stray.pyc'), 'x', 'utf8');

const res = spawnSync('tar', ['-czf', tgz, '-C', tmp, 'package'], { encoding: 'utf8' });
fs.rmSync(tmp, { recursive: true, force: true });
if (res.status !== 0) { process.stderr.write('fake-npm: tar 失败 ' + (res.stderr || res.stdout) + '\n'); process.exit(1); }
process.stdout.write(fname + '\n');
